### ISSUE TITLE
How to clock

### ISSUE THREAD

**Issue by dollebrekel** [rapsta/graphics.pl#1]
Sorry I am new to ubuntu.

my memClock is now running:
Card0 300Mhz - 2150Mhz
Card1 300Mhz - 2150Mhz
Card2 300Mhz - 2150Mhz
Card3 300Mhz - 2150Mhz
Card4 300Mhz - 2150Mhz

How can I change the value can you give you example ?

**Comment by rapsta** [comment]
`./graphics.pl gpuClock `
lists you the possible clocks (you can set this with PolarisBiosEditor)
```
#### card5 has 8 possible settings: ####
 0: 300Mhz
 1: 466Mhz
 2: 751Mhz
 3: 1019Mhz
 4: 1074Mhz
 5: 1126Mhz
 6: 1169Mhz
 7: 1280Mhz *
```

You can than set all gpus to another Level with the same command:
`./graphics.pl gpuClock 5`

You can veriufy the change by list it again and look at the *
```
./graphics.pl gpuClock 
#### card5 has 8 possible settings: ####
 0: 300Mhz
 1: 466Mhz
 2: 751Mhz
 3: 1019Mhz
 4: 1074Mhz
 5: 1126Mhz *
 6: 1169Mhz
 7: 1280Mhz
```

Similar for command `./graphics.pl memClock `
